# Problema

Predecir el tipo de flor

# El set de datos

Número de Instancias:

El conjunto de datos Iris consta de 150 muestras de flores Iris con 4 características cada una.

Características:

* Longitud del sépalo (sepal length)
* Ancho del sépalo (sepal width)
* Longitud del pétalo (petal length)
* Ancho del pétalo (petal width)

Clases o Etiquetas:

* Setosa
* Versicolor
* Virginica

In [30]:
# imports
from sklearn.datasets import load_iris
import numpy as np
import pandas as pd

# Objetivo

Generar un model de clasificación capaz de predecir la clase de flor en función de las carácterísticas del dataset

* Aplicar las técnicas oportunas de procesamiento de datos

* Valorar diferentes modelos de clasificación

* Comparación entre modelos

* Ensemble

* Métricas

* Conclusiones finales

In [32]:
#importamos el csv y comprobamos que es el debemos utilizar para hacer el entregable
df = pd.read_csv('/content/dataset_banco_clean.csv')
df.shape
df

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,58,management,married,tertiary,no,2143.0,yes,no,unknown,5,may,261.0,1,-1.0,0,unknown,no
1,44,technician,single,secondary,no,29.0,yes,no,unknown,5,may,151.0,1,-1.0,0,unknown,no
2,33,entrepreneur,married,secondary,no,2.0,yes,yes,unknown,5,may,76.0,1,-1.0,0,unknown,no
3,47,blue-collar,married,unknown,no,1506.0,yes,no,unknown,5,may,92.0,1,-1.0,0,unknown,no
4,33,unknown,single,unknown,no,1.0,no,no,unknown,5,may,198.0,1,-1.0,0,unknown,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45184,51,technician,married,tertiary,no,825.0,no,no,cellular,17,nov,977.0,3,-1.0,0,unknown,yes
45185,71,retired,divorced,primary,no,1729.0,no,no,cellular,17,nov,456.0,2,-1.0,0,unknown,yes
45186,72,retired,married,secondary,no,5715.0,no,no,cellular,17,nov,1127.0,5,184.0,3,success,yes
45187,57,blue-collar,married,secondary,no,668.0,no,no,telephone,17,nov,508.0,4,-1.0,0,unknown,no
45188,37,entrepreneur,married,secondary,no,2971.0,no,no,cellular,17,nov,361.0,2,188.0,11,other,no

In [33]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder


num_cols = df.select_dtypes(include=['int64', 'float64'])
cat_cols = df.select_dtypes(include=['object'])

# Inicializamos un DataFrame vacío para almacenar las variables categóricas normalizadas
encoded_cat_cols = pd.DataFrame()

# Creamos una instancia de LabelEncoder
label_encoder = LabelEncoder()

# Iteramos sobre las columnas categóricas del DataFrame original
for columna in cat_cols.columns:
    if cat_cols[columna].dtype == 'object':

        encoded_values = label_encoder.fit_transform(cat_cols[columna])
        encoded_cat_cols[columna] = encoded_values


print(encoded_cat_cols)

       job  marital  education  default  housing  loan  contact  month  \
0        4        1          2        0        1     0        2      8
1        9        2          1        0        1     0        2      8
2        2        1          1        0        1     1        2      8
3        1        1          3        0        1     0        2      8
4       11        2          3        0        0     0        2      8
...    ...      ...        ...      ...      ...   ...      ...    ...
45184    9        1          2        0        0     0        0      9
45185    5        0          0        0        0     0        0      9
45186    5        1          1        0        0     0        0      9
45187    1        1          1        0        0     0        1      9
45188    2        1          1        0        0     0        0      9

       poutcome  y
0             3  0
1             3  0
2             3  0
3             3  0
4             3  0
...         ... ..
45184         3  1
45185         3  1
45186         2  1
45187         3  0
45188         1  0

[45189 rows x 10 columns]

In [34]:
from sklearn.preprocessing import MinMaxScaler

df_encoded = df_encoded = pd.concat([num_cols, cat_cols], axis=1)

column_order = ['age', 'job', 'marital', 'education', 'default', 'balance', 'housing', 'loan',
                'contact', 'day', 'month', 'duration', 'campaign', 'pdays', 'previous', 'poutcome', 'y']

df_encoded = df_encoded[column_order]

df_encoded

,age,job,marital,education,default,balance,housing,loan,contact,day,month,duration,campaign,pdays,previous,poutcome,y
0,58,management,married,tertiary,no,2143.0,yes,no,unknown,5,may,261.0,1,-1.0,0,unknown,no
1,44,technician,single,secondary,no,29.0,yes,no,unknown,5,may,151.0,1,-1.0,0,unknown,no
2,33,entrepreneur,married,secondary,no,2.0,yes,yes,unknown,5,may,76.0,1,-1.0,0,unknown,no
3,47,blue-collar,married,unknown,no,1506.0,yes,no,unknown,5,may,92.0,1,-1.0,0,unknown,no
4,33,unknown,single,unknown,no,1.0,no,no,unknown,5,may,198.0,1,-1.0,0,unknown,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45184,51,technician,married,tertiary,no,825.0,no,no,cellular,17,nov,977.0,3,-1.0,0,unknown,yes
45185,71,retired,divorced,primary,no,1729.0,no,no,cellular,17,nov,456.0,2,-1.0,0,unknown,yes
45186,72,retired,married,secondary,no,5715.0,no,no,cellular,17,nov,1127.0,5,184.0,3,success,yes
45187,57,blue-collar,married,secondary,no,668.0,no,no,telephone,17,nov,508.0,4,-1.0,0,unknown,no
45188,37,entrepreneur,married,secondary,no,2971.0,no,no,cellular,17,nov,361.0,2,188.0,11,other,no

In [35]:
import pandas as pd
from sklearn.preprocessing import StandardScaler

#normalizamos las variables númericas en un nuevo df
scaler = StandardScaler()
scaled_num_cols = pd.DataFrame(scaler.fit_transform(num_cols), columns=num_cols.columns)


print(scaled_num_cols)

            age   balance       day  duration  campaign     pdays  previous
0      1.606982  0.195954 -1.298557  0.011211 -0.569436 -0.411352 -0.300937
1      0.288514 -0.342737 -1.298557 -0.416228 -0.569436 -0.411352 -0.300937
2     -0.747425 -0.349617 -1.298557 -0.707664 -0.569436 -0.411352 -0.300937
3      0.571043  0.033633 -1.298557 -0.645491 -0.569436 -0.411352 -0.300937
4     -0.747425 -0.349872 -1.298557 -0.233595 -0.569436 -0.411352 -0.300937
...         ...       ...       ...       ...       ...       ...       ...
45184  0.947748 -0.139900  0.143325  2.793449  0.076445 -0.411352 -0.300937
45185  2.831274  0.090458  0.143325  0.768943 -0.246495 -0.411352 -0.300937
45186  2.925450  1.106174  0.143325  3.376320  0.722327  1.436685  1.271449
45187  1.512806 -0.179907  0.143325  0.971005  0.399386 -0.411352 -0.300937
45188 -0.370720  0.406946  0.143325  0.399791 -0.246495  1.476643  5.464477

[45189 rows x 7 columns]

In [36]:
# Junto en el mismo df las variables categóricas y las variables numéricas normalizadas
df_norm = pd.concat([encoded_cat_cols, scaled_num_cols], axis=1)


print(df_norm)

       job  marital  education  default  housing  loan  contact  month  \
0        4        1          2        0        1     0        2      8
1        9        2          1        0        1     0        2      8
2        2        1          1        0        1     1        2      8
3        1        1          3        0        1     0        2      8
4       11        2          3        0        0     0        2      8
...    ...      ...        ...      ...      ...   ...      ...    ...
45184    9        1          2        0        0     0        0      9
45185    5        0          0        0        0     0        0      9
45186    5        1          1        0        0     0        0      9
45187    1        1          1        0        0     0        1      9
45188    2        1          1        0        0     0        0      9

       poutcome  y       age   balance       day  duration  campaign  \
0             3  0  1.606982  0.195954 -1.298557  0.011211 -0.569436
1             3  0  0.288514 -0.342737 -1.298557 -0.416228 -0.569436
2             3  0 -0.747425 -0.349617 -1.298557 -0.707664 -0.569436
3             3  0  0.571043  0.033633 -1.298557 -0.645491 -0.569436
4             3  0 -0.747425 -0.349872 -1.298557 -0.233595 -0.569436
...         ... ..       ...       ...       ...       ...       ...
45184         3  1  0.947748 -0.139900  0.143325  2.793449  0.076445
45185         3  1  2.831274  0.090458  0.143325  0.768943 -0.246495
45186         2  1  2.925450  1.106174  0.143325  3.376320  0.722327
45187         3  0  1.512806 -0.179907  0.143325  0.971005  0.399386
45188         1  0 -0.370720  0.406946  0.143325  0.399791 -0.246495

          pdays  previous
0     -0.411352 -0.300937
1     -0.411352 -0.300937
2     -0.411352 -0.300937
3     -0.411352 -0.300937
4     -0.411352 -0.300937
...         ...       ...
45184 -0.411352 -0.300937
45185 -0.411352 -0.300937
45186  1.436685  1.271449
45187 -0.411352 -0.300937
45188  1.476643  5.464477

[45189 rows x 17 columns]

In [37]:
#vemos que hemos juntado correctamente ambos df
df_norm.head()

,job,marital,education,default,housing,loan,contact,month,poutcome,y,age,balance,day,duration,campaign,pdays,previous
0,4,1,2,0,1,0,2,8,3,0,1.606982,0.195954,-1.298557,0.011211,-0.569436,-0.411352,-0.300937
1,9,2,1,0,1,0,2,8,3,0,0.288514,-0.342737,-1.298557,-0.416228,-0.569436,-0.411352,-0.300937
2,2,1,1,0,1,1,2,8,3,0,-0.747425,-0.349617,-1.298557,-0.707664,-0.569436,-0.411352,-0.300937
3,1,1,3,0,1,0,2,8,3,0,0.571043,0.033633,-1.298557,-0.645491,-0.569436,-0.411352,-0.300937
4,11,2,3,0,0,0,2,8,3,0,-0.747425,-0.349872,-1.298557,-0.233595,-0.569436,-0.411352,-0.300937

In [38]:
## A completar

# Separamos entre características y variable a predecir
X = df_norm.drop('y', axis = 1)
y = df_norm['y']

In [39]:
from sklearn.naive_bayes import GaussianNB

# Inicializar el clasificador Naive Bayes
nb_classifier = GaussianNB()

# Entrenar el modelo Naive Bayes
nb_classifier.fit(X_train, y_train)

# Predecir en el conjunto de prueba
y_pred_nb = nb_classifier.predict(X_test)

# Calcular la precisión del modelo Naive Bayes
accuracy_nb = accuracy_score(y_test, y_pred_nb)
print("Precisión del modelo Naive Bayes:", accuracy_nb)

Precisión del modelo Naive Bayes: 0.8343660101792432

In [40]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

# Separar características (X) y etiquetas (y)
X = df_norm.drop('y', axis=1)
y = df_norm['y']

# Dividir el conjunto de datos en conjuntos de entrenamiento y prueba
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Inicializar el clasificador KNN
knn_classifier = KNeighborsClassifier(n_neighbors=5)  # Especificamos el número de vecinos (K) como 5

# Entrenar el modelo KNN
knn_classifier.fit(X_train, y_train)

# Realizar predicciones en el conjunto de prueba
y_pred = knn_classifier.predict(X_test)

# Calcular la precisión del modelo
accuracy = accuracy_score(y_test, y_pred)
print("Precisión del modelo KNN:", accuracy)

Precisión del modelo KNN: 0.8932285903961054

In [41]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

## A completar
#probamos con un arbol de decisión para ver como predice

# Separar características (X) y etiquetas (y)
X = df_norm.drop('y', axis=1)
y = df_norm['y']

# Dividir el conjunto de datos en conjuntos de entrenamiento y prueba
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Inicializar el clasificador Random Forest
rf_classifier = RandomForestClassifier(n_estimators=100, random_state=42)  # Especificamos el número de árboles en el bosque

# Entrenar el modelo Random Forest
rf_classifier.fit(X_train, y_train)

# Realizar predicciones en el conjunto de prueba
y_pred = rf_classifier.predict(X_test)

# Calcular la precisión del modelo
accuracy = accuracy_score(y_test, y_pred)
print("Precisión del modelo Random Forest:", accuracy)

Precisión del modelo Random Forest: 0.9089400309803054

In [ ]:
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

# Separar características (X) y etiquetas (y)
X = df_norm.drop('y', axis=1)
y = df_norm['y']

# Dividir el conjunto de datos en conjuntos de entrenamiento y prueba
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Inicializar el clasificador SVM
svm_classifier = SVC(kernel='linear', random_state=42)  # Usamos un kernel lineal para este ejemplo

# Entrenar el modelo SVM
svm_classifier.fit(X_train, y_train)

# Realizar predicciones en el conjunto de prueba
y_pred = svm_classifier.predict(X_test)

# Calcular la precisión del modelo
accuracy = accuracy_score(y_test, y_pred)
print("Precisión del modelo SVM:", accuracy)

Precisión del modelo SVM: 0.8827174153573799

In [ ]:
import xgboost as xgb
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, f1_score
from xgboost import XGBClassifier

# Separar características (X) y etiquetas (y)
X = df_norm.drop('y', axis=1)
y = df_norm['y']

# Dividir el conjunto de datos en conjuntos de entrenamiento y prueba
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Inicializar el clasificador XGBoost
xgb_classifier = XGBClassifier(random_state=42)

# Entrenar el modelo XGBoost
xgb_classifier.fit(X_train, y_train)

# Realizar predicciones en el conjunto de prueba
y_pred = xgb_classifier.predict(X_test)

# Calcular la precisión del modelo
accuracy = accuracy_score(y_test, y_pred)
print("Precisión del modelo XGBoost:", accuracy)

Precisión del modelo XGBoost: 0.9061739322859039
F1 Score del modelo XGBoost: 0.8994693391945198

In [29]:
from sklearn.ensemble import VotingClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import xgboost as xgb
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split

# Separar características (X) y etiquetas (y)
X = df_norm.drop('y', axis=1)
y = df_norm['y']
# Dividir el conjunto de datos en conjuntos de entrenamiento y prueba
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Inicializar cada uno de los clasificadores
knn_classifier = KNeighborsClassifier(n_neighbors=5)
svm_classifier = SVC(kernel='linear', random_state=42)
rf_classifier = RandomForestClassifier(n_estimators=100, random_state=42)
xgb_classifier = xgb.XGBClassifier(random_state=42)

# Crear un ensamble combinando los modelos
ensemble_model = VotingClassifier(estimators=[('knn', knn_classifier), ('svm', svm_classifier),
                                              ('rf', rf_classifier), ('xgb', xgb_classifier)],
                                  voting='hard')  # 'hard' indica votación basada en la mayoría de votos

# Entrenar el ensamble
ensemble_model.fit(X_train, y_train)

# Realizar predicciones en el conjunto de prueba
y_pred = ensemble_model.predict(X_test)

# Calcular la precisión del ensamble
accuracy = accuracy_score(y_test, y_pred)
print("Precisión del ensamble:", accuracy)

Precisión del ensamble: 0.8946669617171941

# Conclusiones

Hemos tenido que normalizar las variables numericas del dataset para que estuviesen todas a escala y no dominase una sobre otra.

En cuanto a la variables categóricas, le aplicamos una etiqueta a cada una de sus opciones, porque no podemos entrenar el modelo con string.

Tras ello, empezamos a probar modelos de predicción y medimos su accuracy en todos para así asegurarnos que estaban evaluados de la misma manera y podemos ver que en el modelo donde obtenemos el mejor accuracy es el random forest.